[workspace]
members = [
    "gooey",
    "frontends/renderers/kludgine",
    "frontends/browser",
    "frontends/rasterizer",
    "core",
    "renderer",
    "text",
    "widgets",
    "xtask",
    "fluent",
    "integrated-examples/bonsaidb/counter/server",
    "integrated-examples/bonsaidb/counter/client",
    "integrated-examples/bonsaidb/counter/shared",
]
resolver = "2"

[patch.crates-io]
# easygpu = { path = "../easygpu/easygpu" }
# easygpu-lyon = { path = "../easygpu/lyon" }
bonsaidb = { git = "https://github.com/khonsulabs/bonsaidb.git", branch = "main" }
# easygpu = { git = "https://github.com/khonsulabs/easygpu.git", branch = "main" }
# easygpu-lyon = { git = "https://github.com/khonsulabs/easygpu.git", branch = "main" }
# bonsaidb = { path="../bonsaidb/bonsaidb" }
# actionable = { git="https://github.com/khonsulabs/actionable.git", branch="main" }
# actionable = { path="../actionable/actionable", version="0.1.0-dev.3" }
# kludgine = { path = "../kludgine/kludgine", version = "0.1.0-dev.0" }
# kludgine = { git = "https://github.com/khonsulabs/kludgine.git", branch = "main", version = "0.1.0-dev.0" }

# [patch."https://github.com/khonsulabs/stylecs.git"]
# stylecs = { path = "../stylecs/stylecs" }

# [patch."https://github.com/khonsulabs/kludgine.git"]

# [patch."https://github.com/khonsulabs/figures.git"]
# figures = { path = "../figures/figures" }

# [patch."https://github.com/khonsulabs/khonsu-tools.git"]
# khonsu-tools = { path="../khonsu-tools" }

# [patch."https://github.com/khonsulabs/bonsaidb.git"]
# bonsaidb = { path="../bonsaidb/bonsaidb" }
