[package]
name = "gooey"
version = "0.1.0"
edition = "2021"

[features]
default = ["web", "desktop"]
web = [
    "gooey-widgets/web",
    "gooey-core/web",
    "dep:gooey-web",
    "dep:wasm-bindgen",
]
desktop = ["raster", "dep:gooey-kludgine"]
raster = ["dep:gooey-raster", "gooey-widgets/raster"]

[dependencies]
gooey-core = { workspace = true }
gooey-widgets = { workspace = true }
gooey-web = { workspace = true, optional = true }
gooey-raster = { workspace = true, optional = true }
wasm-bindgen = { version = "*", optional = true }
log = "0.4"
gooey-kludgine = { workspace = true, optional = true }


[workspace]
members = [
    "crates/gooey-reactor",
    "crates/gooey-core",
    "crates/gooey-raster",
    "crates/gooey-kludgine",
    "crates/gooey-web",
    "crates/gooey-widgets",
    "crates/gooey-macros",
]

[workspace.dependencies]
gooey-core = { path = "crates/gooey-core" }
gooey-kludgine = { path = "crates/gooey-kludgine" }
gooey-macros = { path = "crates/gooey-macros" }
gooey-reactor = { path = "crates/gooey-reactor" }
gooey-raster = { path = "crates/gooey-raster" }
gooey-web = { path = "crates/gooey-web" }
gooey-widgets = { path = "crates/gooey-widgets" }


# [patch.crates-io]
# alot = { git = "https://github.com/khonsulabs/alot" }

# [patch."https://github.com/khonsulabs/stylecs"]
# stylecs = { path = "../stylecs/" }
# stylecs-macros = { path = "../stylecs/stylecs-macros" }
# stylecs-shared = { path = "../stylecs/stylecs-shared" }

# [patch."https://github.com/khonsulabs/kludgine"]
# kludgine = { path = "../kludgine2" }

# [patch."https://github.com/khonsulabs/appit"]
# appit = { path = "../appit" }

# [patch."https://github.com/khonsulabs/figures"]
# figures = { path = "../figures" }


[profile.dev.package]
cosmic-text.opt-level = 3
wgpu.opt-level = 3
kludgine.opt-level = 3
figures.opt-level = 3
