name: Tests

on: [push]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin/cargo-audit
          key: cargo-audit
      - name: Install cargo-audit
        run: cargo -v install cargo-audit
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: Audit
        # TODO Downstream vulnerability: https://rustsec.org/advisories/RUSTSEC-2021-0119
        run: |
          cargo audit -D warnings --ignore RUSTSEC-2021-0119

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Install x11 dependencies for Kludgine
        run: |
          sudo add-apt-repository ppa:kisak/kisak-mesa -y
          sudo apt-get install -yqq \
            libxcb-render-util0-dev \
            libxcb-shape0-dev \
            libxcb-xfixes0-dev \
            mesa-vulkan-drivers \
            ffmpeg

      - name: Run clippy
        run: |
          cargo clippy --all-targets --all-features

      - name: Run unit tests
        run: |
          cargo test --all-features
          cargo test --examples --all-features

  docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Install x11 dependencies for Kludgine
        run: |
          sudo add-apt-repository ppa:kisak/kisak-mesa -y
          sudo apt-get install -yqq \
            libxcb-render-util0-dev \
            libxcb-shape0-dev \
            libxcb-xfixes0-dev \
            mesa-vulkan-drivers \
            ffmpeg
            
      - name: Generate Docs
        run: |
          cargo doc --no-deps --all-features
            
      - name: Generate Example Snapshots
        run: |
          XDG_RUNTIME_DIR="/run/user/$(id -u)" cargo test --examples --all-features
          mv target/snapshots target/doc/

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: target/doc/
          git-config-name: kl-botsu
          git-config-email: botsu@khonsulabs.com
          target-folder: /main/
          clean: true

  book:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin/mdbook
            ~/.cargo/bin/mdbook-linkcheck
            ~/.cargo/bin/mdbook-mermaid
          key: cargo-audit
      - name: Install mdbook
        run: |
          cargo install mdbook --no-default-features --features search
          cargo install mdbook-linkcheck
          cargo install mdbook-mermaid
      - name: Generate book
        run: cd book && mdbook build

      - name: Generate
        uses: JamesIves/github-pages-deploy-action@releases/v4
        if: github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: book/book/html/
          git-config-name: kl-botsu
          git-config-email: botsu@khonsulabs.com
          target-folder: /guide
          clean: true
